type EventList @table {
  id: UUID!            # primary key, explicit
  eventcoord: UUID!
  eventname: String!
  location: String
  eventdesc: String!
  starttime: Timestamp!
  endtime: Timestamp!
  eventstatus: Boolean! @default(value: true)
  lat: Float
  lng: Float
  imageUrl: String
  category: String
  hostUid: String @default(expr: "auth.uid")
}

type UserList @table {
  id: UUID!            # primary key, explicit
  firebaseUid: String @unique
  firstname: String!
  lastname: String!
  email: String! @unique
  password: String!
  age: Int!
  major: String!
}

type Registration @table(name: "registration", key: ["eventId", "userId"]) {
  eventId: UUID! @col(name: "event_id")
  userId: UUID! @col(name: "user_id")
  notif: Boolean @col(name: "notif")
}