type UserList @table {
  userid: UUID!
  firstname: String!
  lastname: String!
  age: Int!
  major: String!
}

type EventList @table {
  eventid: UUID!
  eventcoord: UUID!
  eventname: String!
  eventdesc: String!
  starttime: Timestamp!
  endtime: Timestamp!
}